[project]
name = "nothatsnotsolidsnake"
version = "0.1.0"
description = "A machine learning project that uses computer vision to identify whether an image contains Solid Snake or not, inspired by the â€œNo, thatâ€™s not Solid Snakeâ€ meme."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
